# .github/workflows/caller_test.yaml (修正后)
name: Caller Test Workflow
on:
  workflow_dispatch: # 允许手动触发

jobs:
  call_reusable: # <--- Job ID
    # runs-on: ubuntu-latest # 这个是必须的，即使下面用 uses
    uses: ./.github/workflows/reusable_abc_test.yaml # <--- 在 Job 级别使用 uses
    with:
      target_environment: experimental-env